name: 'Run the merge-json action'

description: 'Run the merge-json action using GitMerger'

inputs:
  json-paths:
    required: false
    description: 'JSON paths to merge'
  main-branch:
    required: false
    description: 'Main branch'
  production-branch:
    required: false
    description: 'Production branch'
  live-mirror-branch:
    required: false
    description: 'Live mirror branch'
  check-json-validity:
    required: false
    description: 'Check JSON validity'
  formatter-command:
    required: false
    description: 'Formatter'
  commit-message:
    required: false
    description: 'Commit message'
  preferred:
    required: false
    description: 'Preferred merge strategy'
  exit-if-no-existing-deployment:
    required: false
    description: 'Exit if no existing deployment'
  run-locally-only:
    required: false
    description: 'Run locally only'

outputs:
  hasConflict:
    description: 'Whether the merge process has conflicts'
  hasErrors:
    description: 'Whether the merge process has errors'
  error:
    description: 'The error message'
  hasCommitted:
    description: 'Whether the merge process has committed'
  mergedFiles:
    description: 'The merged files'
  log:
    description: 'The output of the merge process'

runs:
  using: 'node16'
  main: '../../dist/index.js'
