name: Merge Shopify JSON files from 2 branches

description: 'Merge Shopify JSON files from 2 branches'

author: 'SmartImpact IT'

inputs:
  json-paths:
    required: false
    description: 'JSON paths to merge'
    default: 'config/*.json,locales/*.json,templates/**/*.json'
  main-branch:
    required: false
    description: 'Main branch'
    default: 'main'
  production-branch:
    required: false
    description: 'Production branch'
    default: 'production'
  live-mirror-branch:
    required: false
    description: 'Live mirror branch'
    default: 'live-mirror'
  check-json-validity:
    required: false
    description: 'Check JSON validity'
    default: 'true'
  formatter-command:
    required: false
    description: 'Formatter command'
  commit-message:
    required: false
    description: 'Commit message'
    default: '[AUTOMATED] Update JSON files from `#liveMirror#` branch: #files#'
  push-after-commit:
    required: false
    description: 'Push after commit'
    default: 'true'
  preferred:
    required: false
    description: 'Preferred merge strategy'
    default: 'theirs'
  exit-if-no-existing-deployment:
    required: false
    description: 'Exit if no existing deployment'
    default: 'true'
  run-locally-only:
    required: false
    description: 'Run locally only'
    default: 'true'
  config-git-user:
    required: false
    description: 'Configure git user'
    default: 'true'
  verbose:
    required: false
    description: 'Verbose'
    default: 'false'
  config-file:
    required: false
    description: 'Config file'

outputs:
  hasConflict:
    description: 'Whether the merge process has conflicts'
    value: ${{ steps.merge-json.outputs.hasConflict }}
  hasErrors:
    description: 'Whether the merge process has errors'
    value: ${{ steps.merge-json.outputs.hasErrors }}
  error:
    description: 'The error message'
    value: ${{ steps.merge-json.outputs.error }}
  hasCommitted:
    description: 'Whether the merge process has committed'
    value: ${{ steps.merge-json.outputs.hasCommitted }}
  mergedFiles:
    description: 'The merged files'
    value: ${{ steps.merge-json.outputs.mergedFiles }}
  log:
    description: 'The output of the merge process'
    value: ${{ steps.merge-json.outputs.log }}

runs:
  using: 'composite'
  steps:
    - uses: ruby/setup-ruby@v1
      if: ${{ inputs.check-json-validity == 'true' }}
      with:
        ruby-version: 3.3
        bundler: 'latest'

    - name: Install Shopify CLI
      shell: bash
      if: ${{ inputs.check-json-validity == 'true' }}
      run: npm install -g @shopify/cli @shopify/theme

    - name: Print out the current directory
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
      run: |
        pwd
        echo $GITHUB_ACTION_PATH

    - name: Setup git
      if: ${{ inputs.config-git-user == 'true' }}
      shell: bash
      run: |
        git config --local user.name github-actions
        git config --local user.email github-actions@github.com

    - name: Run the merge code
      id: merge-json
      working-directory: ${{ github.action_path }}
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
        # Set the INPUT_ variables to the values of the action.yml inputs. These are not available in composite actions, so we have to pass them in manually.
        # https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#example-specifying-inputs
        INPUT_JSON_PATHS: ${{ inputs.json-paths }}
        INPUT_MAIN_BRANCH: ${{ inputs.main-branch }}
        INPUT_PRODUCTION_BRANCH: ${{ inputs.production-branch }}
        INPUT_LIVE_MIRROR_BRANCH: ${{ inputs.live-mirror-branch }}
        INPUT_CHECK_JSON_VALIDITY: ${{ inputs.check-json-validity }}
        INPUT_FORMATTER_COMMAND: ${{ inputs.formatter-command }}
        INPUT_COMMIT_MESSAGE: ${{ inputs.commit-message }}
        INPUT_PREFERRED: ${{ inputs.preferred }}
        INPUT_EXIT_IF_NO_EXISTING_DEPLOYMENT: ${{ inputs.exit-if-no-existing-deployment }}
        INPUT_RUN_LOCALLY_ONLY: ${{ inputs.run-locally-only }}
        INPUT_CONFIG_GIT_USER: ${{ inputs.config-git-user }}
        INPUT_VERBOSE: ${{ inputs.verbose }}
        INPUT_CONFIG_FILE: ${{ inputs.config-file }}
      run: |
        pwd
        node dist/index.js

    - name: Output the log
      shell: bash
      run: |
        echo "${{ steps.merge-json.outputs.log }}"

    - name: See the git status
      shell: bash
      run: |
        git status

    - name: Check JSON validity, if requested
      shell: bash
      if: ${{ steps.merge-json.outputs.hasCommitted == 'true' && inputs.check-json-validity == 'true' }}
      run: |
        git status | grep 'Your branch is ahead' && shopify theme check -c json

    - name: Push the changes, if there are any
      shell: bash
      if: ${{ inputs.push-after-commit == 'true' && steps.merge-json.outputs.hasCommitted == 'true' }}
      run: |
        git status | grep 'Your branch is ahead' && git push && echo 'Pushed changes' || echo "No changes to push"
